image: jupyter/scipy-notebook

pages:
  script:
  - apt-get install python3-pip make
  - pip3 install tgt sphinx
  - cd doc
  - make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
