image: debian

pages:
  script:
  - apt-get update
  - apt-get install python3-pip make python3-numpy python3-scipy python3-pandas python3-sphinx
  - pip3 install tgt
  - cd doc
  - make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
