image: debian

pages:
  script:
  - apt-get update
  - apt-get install --assume-yes --no-install-recommends make python3-pip python3-setuptools
  - pip3 install numpy scipy pandas matplotlib sphinx tgt
  - cd doc
  - make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
